spring:
  application:
    name: servicediscovery
  security:
    user:
      name: admin
      password: admin
server:
  port: 9090
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://admin:admin@localhost:9090/eureka/
    server:
      enable-self-preservation: true
