spring:
  application:
    name: userservice
  redis:
    host: redis
    port: 6379
server:
  port: 8125

eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:9090/eureka
    healthcheck:
      enabled: true
    lease:
      duration: 5

management:
  security:
    enabled: false

logging:
  level:
    com.us: DEBUG